export const EXERCISE_SUGGESTIONS: Record<string, string[]> = {
  Peito: [
    'Supino reto',
    'Supino inclinado',
    'Supino declinado',
    'Crucifixo',
    'Flexão de braço',
    'Peck deck',
    'Crossover na polia',
    'Supino com halteres',
  ],
  Costas: [
    'Puxada frontal',
    'Barra fixa',
    'Remada curvada',
    'Remada unilateral',
    'Levantamento terra',
    'Pulldown',
    'Remada baixa',
    'Pullover',
  ],
  Ombros: [
    'Desenvolvimento militar',
    'Elevação lateral',
    'Elevação frontal',
    'Remada alta',
    'Crucifixo invertido',
    'Arnold press',
    'Desenvolvimento com halteres',
  ],
  Bíceps: [
    'Rosca direta',
    'Rosca alternada',
    'Rosca martelo',
    'Rosca concentrada',
    'Rosca scott',
    'Rosca 21',
    'Rosca na polia',
  ],
  Tríceps: [
    'Tríceps pulley',
    'Tríceps testa',
    'Mergulho',
    'Tríceps francês',
    'Extensão de tríceps',
    'Kickback',
    'Supino fechado',
  ],
  Pernas: [
    'Agachamento livre',
    'Leg press',
    'Afundo',
    'Cadeira extensora',
    'Cadeira flexora',
    'Stiff',
    'Hack squat',
    'Agachamento búlgaro',
  ],
  Glúteos: [
    'Hip thrust',
    'Elevação pélvica',
    'Agachamento sumô',
    'Abdução de quadril',
    'Glute bridge',
    'Passada',
    'Cadeira abdutora',
  ],
  Abdômen: [
    'Abdominal crunch',
    'Prancha',
    'Elevação de pernas',
    'Abdominal oblíquo',
    'Russian twist',
    'Mountain climber',
    'Abdominal na polia',
  ],
  Panturrilha: [
    'Panturrilha em pé',
    'Panturrilha sentado',
    'Panturrilha no leg press',
    'Panturrilha unilateral',
    'Panturrilha no step',
  ],
  'Corpo inteiro': [
    'Burpee',
    'Kettlebell swing',
    'Thruster',
    'Levantamento terra',
    'Clean and press',
    'Circuito funcional',
  ],
  Cardio: [
    'Corrida',
    'Bicicleta ergométrica',
    'Elíptico',
    'Polichinelo',
    'Corda',
    'HIIT',
    'Escada',
  ],
};

export function getExerciseSuggestions(muscleGroup: string, existingNames: string[] = []): string[] {
  const suggestions = EXERCISE_SUGGESTIONS[muscleGroup] ?? [];
  const used = new Set(existingNames.map(n => n.toLowerCase().trim()));
  return suggestions.filter(s => !used.has(s.toLowerCase()));
}
